### PR TITLE
Fix hoisting transpose before broadcasts

### LINKED ISSUE #546: Shape mismatch due to invalid erase inverse ops operation
Due to invalid transpose op removal in erase inverse ops pass, there is a shape mismatch issue based on invalid commute shape calculation.

Repro steps
```bash
$ git checkout akannan/test_mismatch_sanity
$ git submodule update --init --recursive -f
$ pytest -svv forge/test/model_demos/high_prio/cnn/pytorch/test_shape_mismatch.py::test_wideresnet_pytorch[no_device-wide_resnet50_2]
```

Before Erase Inverse Ops:
image (4)

After Erase Inverse Ops:
image (5)

### LINKED ISSUE #565: Broadcast TMs are improperly commuted through transpose op
Inside erase inverse ops pass we try to commute broadcast tms through transpose op clone (try_commute_bcast_through_clone).

By moving broadcasts after transpose we have to change broadcast dim if it was included in transpose (if broadcast dim is -2 and transpose is between -3 and -2 new broadcast dim becomes -3 because transpose changed the axis we want to broadcast on...)

This is not done properly and causes shape missmatch issue #546.

### PR DESCRIPTION
**Pull request by dgolubovicTT**
Closes #565 (and closes #546)

Add proper update to broadcast dim when commuting broadcast through transpose.

Explanation:
We want to hoist transpose to be before broadcast because then transpose will be optimized out in consteval... By moving broadcasts after transpose we have to change broadcast dim if it was included in transpose (if broadcast dim is -2 and transpose is between -3 and -2 new broadcast dim becomes -3 because transpose changed the axis we want to broadcast on...)

### CODE REVIEW

**Review by LPanosTT — APPROVED** [review]
LGTM 🔥

**Comment by ashokkumarkannan1** [comment]
> FYI @ashokkumarkannan1 :)) Seems like your issues is resolved :)) Feel free to review and and post comments if you have some suggestions based on your exploration :))

This fix seems good to me and more valid @nvukobratTT .

**Review by ashokkumarkannan1 — APPROVED** [review]

File: forge/csrc/passes/commute_utils.cpp [hunk 1]
```diff
@@ -1282,15 +1295,12 @@ bool try_commute_bcast_through_clone(graphlib::Graph *graph, graphlib::OpNode *n
...
-                if (dim == -1 or dim == -2)
-                {
-                    erase_tms.push_back(i);
-                    dim = (dim == -1) ? -2 : -1;  // flip the dim
-                    updated_shape[dim] = operand_dim_size;
-                    std::get<int>(op_type.attr[0]) = dim;
-                    for (auto user_edge : graph->user_data_edges(op))
-                        graph->get_edge_attributes(user_edge)->prepend_tm(op_type);
-                }
+                erase_tms.push_back(i);
```
Comment (nvukobratTT) [inline forge/csrc/passes/commute_utils.cpp:1298]: Let's add comment (s) explaining following logic

File: forge/csrc/passes/commute_utils.cpp [hunk 2]
```diff
@@ -1008,6 +1008,19 @@ void restore_bcast_on_condition(
     }
 }
 
+int update_bcast_dim_commuted_through_transpose(int dim, graphlib::OpNode *op)
```
Comment (nvukobratTT) [inline forge/csrc/passes/commute_utils.cpp:1011]: Can we add a unit test to cover added function/logic? 

E.g. similar to other tests for this pass `forge/csrc/test/passes/test_erase_inverse_ops.cpp`

File: forge/csrc/passes/commute_utils.cpp (hunk 1 above)
Comment (dgolubovicTT) [reply forge/csrc/passes/commute_utils.cpp:1298]: Since all logic is in `update_bcast_dim_commuted_through_transpose` added coments to explain how we get new broadcast dim...

File: forge/csrc/passes/commute_utils.cpp (hunk 2 above)
Comment (dgolubovicTT) [reply forge/csrc/passes/commute_utils.cpp:1016]: Done. Added the same case we reproed in #546

**Review by nvukobratTT — APPROVED** [review]

File: forge/csrc/test/passes/test_erase_inverse_ops.cpp [hunk 3]
```diff
@@ -223,3 +226,54 @@ TEST_F(EraseInverseOps, replace_x_y_change_concat_pattern)
...
+            *graph, "transpose", graphlib::OpType("transpose", {}, {}, {{"dim0", -3}, {"dim1", -2}}), {in0_a});
+
+        // There is only one edge between in0_a and transpose nodes.
+        graphlib::Edge edge_with_bcst = graph->get_edges(in0_a, transpose)[0];
+        // Add broadcast to the edge
+        graph->get_edge_attributes(edge_with_bcst)->set_broadcast_dim(-2, 112);
+        graph->get_edge_attributes(edge_with_bcst)->set_broadcast_dim(-1, 112);
+
+        tt::graphlib::InputNode *in1_b = create_input(*graph, "in1_b", shapeT);
+        auto multiply = add_node<graphlib::PyOpNode>(*graph, "multiply", "multiply", {}, {transpose, in1_b});
```
Comment (nvukobratTT) [inline forge/csrc/test/passes/test_erase_inverse_ops.cpp:252]: Can we use specific types?

Comment (dgolubovicTT) [reply forge/csrc/test/passes/test_erase_inverse_ops.cpp:252]: ofc
