### PR TITLE
Fix: Update dim in named attrs of concat op

### LINKED ISSUE #651: error: 'ttir.concat' op All input tensors must have the same dimensions, except for dimension 1 for dla
## Description

- ` loc("concatenate_312"("forward":4294967295:2706)): error: 'ttir.concat' op All input tensors must have the same dimensions, except for dimension 1.` for dla variants mentioned in branch.

## Reproduce

```
git checkout mramanathan/dla_concat
git submodule update --recursive
 pytest forge/test/model_demos/high_prio/cnn/pytorch/test_dla.py -vss
```

## Observed Behaviour
```
loc("concatenate_312"("forward":4294967295:2706)): error: 'ttir.concat' op All input tensors must have the same dimensions, except for dimension 1.
loc("pt_dla34":0:0): error: module verification failed.
```

### PR DESCRIPTION
**Pull request by meenakshiramanathan1**
Fixes #651 

- variants in DLA were failing due to error: 'ttir.concat' op All input tensors must have the same dimensions, except for dimension 1

Before fix - [dla1.log](https://github.com/user-attachments/files/17720113/dla1.log)

After fix - [dla.log](https://github.com/user-attachments/files/17720133/dla.log)

### CODE REVIEW

**Review by nvukobratTT — COMMENTED** [review]
Is this model fully compiled now?

**Comment by meenakshiramanathan1** [comment]
> Is this model fully compiled now?

Yes, it's being fully compiled now

[dla.log](https://github.com/user-attachments/files/17725958/dla.log)

**Review by nvukobratTT — APPROVED** [review]

**Comment by meenakshiramanathan1** [comment]
> Is this model fully compiled now?

@nvukobratTT , yes it is fully compiled, but when trying to run the compiled model , it is failing in runtime with issue #609

**Comment by dgolubovicTT** [comment]
This [PR](https://github.com/tenstorrent/tt-forge-fe/pull/672) is solving the #609 problem. It will be in main today, so please verify if the test passes with it.

**Review by dgolubovicTT — APPROVED** [review]

File: forge/csrc/passes/commute_utils.cpp [hunk 1]
```diff
@@ -539,7 +539,11 @@ bool commute_through_concat(
         concat_golden_transform.attr[concat_dim >= 0 ? concat_dim : concat_dim + concat_golden_transform.attr.size()] =
             concat_output_len;
     op->add_golden_transform(concat_golden_transform);
-    op->overwrite_op_attrs(attr);
+    std::vector<graphlib::OpType::Attr> concat_attr;
+    concat_attr.push_back(new_dim);
```
Comment (dgolubovicTT) [inline forge/csrc/passes/commute_utils.cpp:543]: @meenakshiramanathan1 we have this overwrite_op_attrs on many places in this part of the stack. Can you create an issue to transition to named attributes? This will bite us little by little if we solve only partial cases like this one. I would ask you to follow up on this PR with another one fixing this throughout the commute_utils. Does this sound reasonable?

Comment (meenakshiramanathan1) [reply forge/csrc/passes/commute_utils.cpp:543]: Sure @dgolubovicTT , I will create an issue and follow up with another PR with changes transitioning to named attributes.
